### ISSUE TITLE
关于链表的 double free 问题

### ISSUE THREAD

**Issue by HangX-Ma** [Pokerpoke/LeetCode#7]
您好，我在使用这个repo做链表题目的时候 `leetcode problem 207` 发现会出现 `free(): double free detected in tcache 2` 报错。我在代码里看到这样一段：

```cpp
  // 是否删除链表
  // 某些题目中会使用两个链表，删除两次会出错
  // 开启后会造成内存泄漏
  void setRelease(bool release = true);
```

我试着用 **valgrind** 定位这个问题，发现如果 `release = true`， 则会多出 4 个 `free` 过程。而这个问题仅在测例为如下情况时才出现：

```cpp
TEST(remove_linked_list_elements, remove_linked_list_elements_case3)
{
    Solution s;
    List in = {7, 7, 7, 7};
    List ans = {};
    int val = 7;
    // in.no_release();
    // ans.no_release();

    EXPECT_TRUE(is_same_list(s.removeElements(in.head, val), ans.head));
}
```
请问您是如何定位这个问题，并通过这种方式解决 double free 的？我尝试了一个晚上，没有丝毫头绪，希望得到您的回复！十分感谢！

**Comment by Pokerpoke** [comment]
比如在合并链表的情况下，L1和L2会有一个重叠的Node1，L1析构的时候会把Node1释放掉，L2析构的时候到Node1的时候就会产生double free了，比较好的方法是加一个引用计数，类似智能指针一样的，但这个是练习算法的项目，可以不用太在意内存泄漏，就没有处理了😂

**Comment by HangX-Ma** [comment]
> 比如在合并链表的情况下，L1和L2会有一个重叠的Node1，L1析构的时候会把Node1释放掉，L2析构的时候到Node1的时候就会产生double free了，比较好的方法是加一个引用计数，类似智能指针一样的，但这个是练习算法的项目，可以不用太在意内存泄漏，就没有处理了😂

😭 207题甚至不是合并链表，是个单链表，要求创建 L1 并删除里面的元素，连续删 head 把 L1 都清空了就出现了这个问题。

所以我觉得很奇怪，现在的情况是单链表，并且在析构函数里面也有判断 node 是否为`nullptr` 的条件语句，我在每次删除元素后都有将删除的 node 设置为 `nullptr`。因此我很怀疑析构函数的某处逻辑存在问题（debug 报错也是在 `~List`中）。

另外我有用 valgrind 测了一下，我把输入的 7 的个数改成 3 个， double free 的次数也随之减少为 3 个。

![image](https://github.com/Pokerpoke/LeetCode/assets/60278513/57cde7e8-3869-4e4f-8791-708dd73ae60e)

**Comment by Pokerpoke** [comment]
删除以后，父节点的next置空了嘛

**Comment by HangX-Ma** [comment]
> 删除以后，父节点的next置空了嘛

找到问题了，父节点 `next` 没设置 `nullptr` 导致了 4 次 `double free` 中的 3 次，另外一个比较关键的是参数传递的方式：

```cpp
ListNode *removeElements(ListNode *head, int val);
```

leetcode 给的函数声明传入的 `head` 指针，相当于给到了 `head` 指向的内存地址，但是没有传入 `head` 本身所在的地址，因而无法在  `removeElements` 中改变 `head` 影响到外部的 `List` 成员函数的 `head`。这导致了头节点的一次 `double free`.

测试函数写成如下形式就能保证没有内存泄漏了：

```cpp
TEST(remove_linked_list_elements, remove_linked_list_elements_case3)
{
    Solution s;
    List in = {7, 7, 7, 7};
    List ans = {};
    int val = 7;
    // in.no_release();
    // ans.no_release();

    EXPECT_TRUE(is_same_list(s.removeElements(in.head, val), ans.head));
    in.head = nullptr;
}
```

谢谢 @Pokerpoke ，可以在 `template0.cc` 写个注释提醒一下这个问题 😆
